image: node:10.11.0

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

tests:
  stage: test
  script:
    - git submodule update --init --recursive
    - npm rebuild
    - npm install
    - npm test

deploy:
  stage: deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - if [ $(npm view $(node -p "require('./package.json').name") version) != $(node -p "require('./package.json').version") ]; then npm publish ; fi
