build:
  environment:
    node: '10.11.0'
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
    tests   : true
  tests:
    override:
      - npm test
checks:
  javascript: true
