build:
  environment:
    node: "v10.11.0"
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
    test:
      tests:
        override:
          - npm test
  tests:
    override:
      - true

#build:
#  environment:
#    node: '10.11.0'
#  nodes:
#    analysis:
#      tests:
#        override:
#          - js-scrutinizer-run
#  tests:
#    override:
#      - npm test
##checks:
##  javascript: true
